#!/usr/bin/env bash
# Fetch third-party OpenAPI reference specs for conformance checking and response validation.
#
# Usage:
#   ./scripts/fetch-openapi-specs.sh           # Fetch all specs
#   ./scripts/fetch-openapi-specs.sh openai    # Fetch only OpenAI spec
#   ./scripts/fetch-openapi-specs.sh anthropic # Fetch only Anthropic spec
#   ./scripts/fetch-openapi-specs.sh openrouter # Fetch only OpenRouter spec
#
# These files are gitignored and must be fetched before:
#   - Running the conformance checker (scripts/openapi-conformance.py)
#   - Building with response-validation feature (uses openai.openapi.json at compile time)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OPENAPI_DIR="$ROOT_DIR/openapi"

# --- Source URLs ---
# OpenAI: https://github.com/openai/openai-openapi (now hosted on Stainless)
OPENAI_YAML_URL="https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml"
# Anthropic: URL resolved dynamically from .stats.yml in the SDK repo (spec is generated by Stainless)
ANTHROPIC_STATS_URL="https://raw.githubusercontent.com/anthropics/anthropic-sdk-typescript/main/.stats.yml"
# OpenRouter: https://openrouter.ai/docs
OPENROUTER_YAML_URL="https://openrouter.ai/openapi.yaml"

download() {
    local url="$1" output="$2"
    echo "  Downloading $(basename "$output") ..."
    if command -v curl &>/dev/null; then
        curl -sSfL "$url" -o "$output"
    elif command -v wget &>/dev/null; then
        wget -q "$url" -O "$output"
    else
        echo "Error: Neither curl nor wget found." >&2
        exit 1
    fi
}

yaml_to_json() {
    local input="$1" output="$2"
    echo "  Converting $(basename "$input") -> $(basename "$output") ..."
    python3 -c "
import json, sys, datetime
try:
    import yaml
except ImportError:
    sys.exit('Error: PyYAML not installed. Run: pip install pyyaml')
class Encoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, (datetime.date, datetime.datetime)):
            return o.isoformat()
        return super().default(o)
with open('$input') as f:
    data = yaml.safe_load(f)
with open('$output', 'w') as f:
    json.dump(data, f, indent=2, cls=Encoder)
"
}

resolve_anthropic_url() {
    echo "  Resolving Anthropic spec URL from .stats.yml ..."
    local stats
    if command -v curl &>/dev/null; then
        stats="$(curl -sSfL "$ANTHROPIC_STATS_URL")"
    elif command -v wget &>/dev/null; then
        stats="$(wget -qO- "$ANTHROPIC_STATS_URL")"
    else
        echo "Error: Neither curl nor wget found." >&2
        exit 1
    fi
    ANTHROPIC_YAML_URL="$(echo "$stats" | grep '^openapi_spec_url:' | sed 's/^openapi_spec_url: *//')"
    if [[ -z "$ANTHROPIC_YAML_URL" ]]; then
        echo "Error: Could not resolve Anthropic OpenAPI spec URL from .stats.yml" >&2
        exit 1
    fi
}

fetch_openai() {
    echo "Fetching OpenAI spec..."
    download "$OPENAI_YAML_URL" "$OPENAPI_DIR/openai.openapi.yml"
    yaml_to_json "$OPENAPI_DIR/openai.openapi.yml" "$OPENAPI_DIR/openai.openapi.json"
    echo "  Done."
}

fetch_anthropic() {
    echo "Fetching Anthropic spec..."
    resolve_anthropic_url
    download "$ANTHROPIC_YAML_URL" "$OPENAPI_DIR/anthropic.openapi.yml"
    yaml_to_json "$OPENAPI_DIR/anthropic.openapi.yml" "$OPENAPI_DIR/anthropic.openapi.json"
    echo "  Done."
}

fetch_openrouter() {
    echo "Fetching OpenRouter spec..."
    download "$OPENROUTER_YAML_URL" "$OPENAPI_DIR/openrouter.openapi.yml"
    echo "  Done."
}

# --- Main ---
target="${1:-all}"

case "$target" in
    openai)     fetch_openai ;;
    anthropic)  fetch_anthropic ;;
    openrouter) fetch_openrouter ;;
    all)
        fetch_openai
        fetch_anthropic
        fetch_openrouter
        echo ""
        echo "All reference specs fetched into openapi/"
        ;;
    *)
        echo "Usage: $0 [openai|anthropic|openrouter|all]" >&2
        exit 1
        ;;
esac
